### ISSUE TITLE
Webhook is not accepting case requires_payment_method

### ISSUE THREAD

**Issue by flowroma** [stripe/stripe-php#1386] opened 2022-10-25 18:42 UTC
### Describe the bug

Sometimes customers initiate a payment, but then leave the page without picking a payment method. I get the status incomplete with payment intent status: requires_payment_method. 

When making a webhook case for payment_intent.requires_payment_method, it does not work. There is nothing wrong with the code, because when I put it inside a payment_intent.succeeded or payment_intent.payment_failed case, it works. 

Is this a bug? How can it be solved. 

### To Reproduce

```
switch ($event->type) {
      case 'payment_intent.requires_payment_method':
         //code to delete user's data when no payment method is chosen and the cart is abandoned. 
      break;
}
```

### Expected behavior

I expect the code inside the case to execute. However, when setting the case to payment_intent.succeeded or payment_intent.payment_failed, it does work as intended.

**Comment by yejia-stripe** [comment] 2022-10-25 19:13
Hi @flowroma, thanks for the report! There is no `payment_intent.requires_payment_method` event (see [Types of events](https://stripe.com/docs/api/events/types) in the API Reference), so this is not a bug with stripe-php. 

As this is not a bug with the library, I'm going to close this issue. If you need help with your integration, please reach out to [Support](https://support.stripe.com/) instead (sorry can't be of more help here).

**Closed by yejia-stripe** 2022-10-25 19:13 UTC
Labels: bug
