### ISSUE TITLE
API extremely slow?

### ISSUE THREAD

**Issue by SteveEdson** [stripe/stripe-php#171] opened 2015-06-23 14:28 UTC
I have a database containing some subscription plans, with a stripe ID.

When I get a list of the plans, I want to pull in the associated stripe plan info for each one.

```php
    $start = microtime(true);
    Plan::retrieve('plan_id');
    $end = microtime(true);

    echo "Total time: " . round($end - $start, 4);
```

The following code is taking ~`1.07 - 2.01` seconds for each call. When I have ~6 different plans to show, this can really slow the page down.

Is this an issue, or is this intended? I'm happy to cache the data if necessary, I'm just not sure if the API is supposed to be that slow.

Thanks,

Steve

**Comment by matthewarkin** [comment] 2015-06-23 14:33
@SteveEdson If you just do a curl request `curl https://api.stripe.com/v1/plans -u <api key>:` does that similiarly take as long?

Though you probably don't want to use Stripe as a database and make an API call to get all 6 plans per page load.

**Comment by SteveEdson** [comment] 2015-06-23 14:44
Unfortunately. The command:

```sh
$ curl https://api.stripe.com/v1/plans -u my_key -s -w "@curl-format.txt"
```

Produces:

```
    time_namelookup:  0.068
       time_connect:  0.317
    time_appconnect:  1.145
   time_pretransfer:  1.145
      time_redirect:  0.000
 time_starttransfer:  1.486
                    ----------
         time_total:  1.487
```

I'll look into caching the data, or not using it until it is required.

**Comment by bkrausz** [comment] 2015-06-24 04:52
Hi @SteveEdson. From the 8 curl requests you made at that time to /v1/plans, I see all of them taking under 100ms from the time they hit our servers to the time we send out a response.

It looks like, from your timing data, that almost all the time is spent in the SSL handshake. You are hopping from the UK to the US west coast, but even then .8s is still quite a long time.

Is this being run on your personal machine, or your production server? If it's going over a consumer internet connection I wouldn't consider that too surprising, but if it's from a reasonable datacenter I'm happy to dig further.

Feel free to continue commenting so we can dig into this, though I'm closing this issue out as it's not a bug with our PHP bindings.

**Closed by bkrausz** 2015-06-24 04:52 UTC

**Comment by SteveEdson** [comment] 2015-06-24 08:08
No problem.

That was on my personal machine over a 50Mb connection, however we're seeing times of ~1s from a EC2 instance in eu-west-1b.

**Comment by bkrausz** [comment] 2015-06-25 02:50
K, it sounds like it's a eu-west thing then, and there's nothing we can do in the immediate future (barring an EU server presence).
