### ISSUE TITLE
Could it be that autoPagingIterator is losing initial params?

### ISSUE THREAD

**Issue by tishma** [stripe/stripe-php#1055] opened 2020-12-02 23:37 UTC
In effect - I'm collecting all invoices for a customer, and since my customer has more than 1 (10-item) page worth of invoices - subsequent requests seem to be collecting other customers' invoices as well, as long as they match `starting_after` condition. If I increase limit to capture all invoices in a single request - I'm only getting single customer's invoices - as expected.

I have a reason to believe that in this setup - subsequent requests made thru `autoPagingIterator` are not keeping the parameters. If that's intended - I'd really appreciate the hint on how to achieve the above.

```
$invoices = $stripeClient->invoices->all(['customer' => $this->stripeCustomer->id, 'expand' => ['data.charge', 'data.subscription']]);
foreach ($invoices->autoPagingIterator() as $invoice) {
               ....
```

php-stripe version: 7.333
php version: 7.4.11

**Comment by remi-stripe** [comment] 2020-12-03 01:23
@tishma Thanks for reaching out! I tried to reproduce locally but the code is working properly for me. Here's what I'm doing:

```
$invoices = $stripe->invoices->all([
  'customer' => 'cus_12345',
  'limit' => 1,
]);

foreach ($invoices->autoPagingIterator() as $invoice) {
    echo "Invoice id: '" . $invoice->id . "' - Customer id: '" . $invoice->customer . "'<br>";
}
```

When I run that code, I get one invoice per page and I'm properly paginating through all the invoices of my customer and only that one.

Would you be able to try something similar on your end with the right customer id to confirm you're seeing the same thing?

**Comment by tishma** [comment] 2020-12-03 22:04
Hey, thanks for the response. I have collected 2 pieces of evidence using your method. I only have 2 customers (A and B), so I'm virtually dumping all invoices I've got in my test. Customer B has just 2 invoices, and one is the oldest one while the other is the 5th recent.
1. I'm looping through all invoices for either of the customers (most recent coming first - by default), and the conclusion is that customer A pretty much shows all invoices (being the owner of the most recent one), while customer B starts with her most recent invoice and again - picks all the remaining ones. Here is the output - left hand customer id is from the invoice returned from the API, and right hand one was used to initiate the query.
```
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_INWUfMGGTDBTOa---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_INWUfMGGTDBTOa---cus_IOBi5peXpo8Nz9
cus_INWUfMGGTDBTOa---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_IOBi5peXpo8Nz9---cus_INWUfMGGTDBTOa
cus_INWUfMGGTDBTOa---cus_INWUfMGGTDBTOa
```
2. My other evidence is that data.charge only expanded on the first iteration, and only shows charge id onwards. I didn't bother to check if subscription expands though.
<img width="1081" alt="Screenshot 2020-12-03 at 22 36 43" src="https://user-images.githubusercontent.com/4130604/101093770-9e8b0700-35bb-11eb-9e02-470aed1d4f30.png">
<img width="1090" alt="Screenshot 2020-12-03 at 22 37 26" src="https://user-images.githubusercontent.com/4130604/101093745-9206ae80-35bb-11eb-934e-801e1e201279.png">

```
        $invoices = $stripeClient->invoices->all(['customer' => $this->stripeCustomer->id, 'limit' => 1, 'expand' => ['data.charge', 'data.subscription']]);
        /** @var Invoice $invoice */
        foreach ($invoices->autoPagingIterator() as $invoice) {
            echo $invoice->customer, '---',  $this->stripeCustomer->id, '<br>';
```

**Comment by remi-stripe** [comment] 2020-12-03 22:17
@tishma okay the issue is that you are on an older version of stripe-php that had the bug which we fixed back in May in https://github.com/stripe/stripe-php/pull/942 which was released in 7.36.1. If you upgrade to that version (or rather the latest), it will fix the problem

**Comment by tishma** [comment] 2020-12-03 22:26
Okay, trying.
However, my version was `7.62` which is documented to be less than a month old...
`  - Updating stripe/stripe-php (v7.62.0 => v7.66.1)`

**Comment by tishma** [comment] 2020-12-03 22:28
But it sure is fixed now!
```
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_IOBi5peXpo8Nz9---cus_IOBi5peXpo8Nz9
cus_INWUfMGGTDBTOa---cus_INWUfMGGTDBTOa
cus_INWUfMGGTDBTOa---cus_INWUfMGGTDBTOa
```

**Comment by tishma** [comment] 2020-12-03 22:32
I'm still gonna go for the max limit in order not to throw so many requests at the API, but this is will not going to be another thing to keep me awake at night :)

**Comment by remi-stripe** [comment] 2020-12-04 02:34
Awesome, glad you got unblocked!

**Closed by remi-stripe** 2020-12-04 02:34 UTC
