### ISSUE TITLE
Create a Card

### ISSUE THREAD

**Issue by Grafikart** [stripe/stripe-php#363] opened 2017-07-17 09:57 UTC
Hello

Is there a way to create a card from this library ?
I want to translate [this call](https://stripe.com/docs/api#create_card) but the Card Class doesn't contain a `create` method.

I could do a PR to add these features but the use of static method is a problem, this class would have to overwrite the _create, _list, _update methods from ApiResource (since the URL expects a parameter).

```php

class Card extends ApiResource
{

    public static function create(string $customer, ?array $params = null, ?array $options = null): StripeObject
    {
        self::_validateParams($params);
        $url = "/v1/customers/" . $customer . "/sources";
        [$response, $opts] = static::_staticRequest('post', $url, $params, $options);
        $obj = Util::convertToStripeObject($response->json, $opts);
        $obj->setLastResponse($response);
        return $obj;
    }

}
```

**Comment by remi-stripe** [comment] 2017-07-17 12:16
@Grafikart You don't need to add anything as it's already supported in the library and covered in the documentation. To create a card right now you have to go through the Customer who owns it. The code looks like this:

```
$customer = \Stripe\Customer::retrieve("cus_XXXXX");
$customer->sources->create(array("source" => "tok_visa"));
```

**Comment by Grafikart** [comment] 2017-07-17 12:32
Feel free to ignore this comment if you don't agree (this is an opinion, i'm not trying to enforce my point of view :))

Your answer does the job but it forces you to do 2 API calls to create a card. Moreover, I think the method "create" you are showing is not as obvious as others (I could guess the other methods reading from the Stripe API).

**Comment by remi-stripe** [comment] 2017-07-17 12:54
@Grafikart Ah okay I see what you're asking now. You want to create a card in one API call as is done in some other libraries like the Node.js one?

If so it would definitely be useful to add but not specifically for cards as the path is the same for any `Source` really including ACH, SEPA, etc. The issue is that passing a `$customerId` as the first parameter feels weird and not something we do in other resources in the PHP library.

A different fix would be to special-case the `$params['customer']` to change the URL we submit too in the [create](https://github.com/stripe/stripe-php/blob/master/lib/Source.php#L43) call but I'm not sure it's the kind of "hacks" we'd want in the library.

cc @brandur-stripe  @ob-stripe for thoughts?

**Comment by evan-stripe** [comment] 2017-07-17 13:00
Hmm. I think most of our other libraries have a constructor that lets you create an object from an ID without having to fetch it, e.g.

```ruby
customer = Stripe::Customer.new('cus_123abc')
customer.sources.create(blah: blah)
```

**Comment by remi-stripe** [comment] 2017-07-17 13:08
@evan-stripe Doesn't that feel wrong though? Sounds more like a hack than a reliable solution to rely on the fact that passing an id will set it in the right place. In that case I definitely prefer either adding `$customerId` to the Source creation or adding a `createSource()` to the `Customer` class.

**Comment by Grafikart** [comment] 2017-07-17 13:54
The problem could be also expanded to retrieve sources from a customer

```php
$customer = new Customer('cus_123abs');
$customer->createSource(); // Create a new source 
$customer->sources(); // Retrieve the sources for this customer
```

Or to keep consistancy with the rest of the library, keeping everything static :

```php
Source::all(['customer' => 'cus_abc']);
Source::create(['customer' => 'cus_abc']);
```

**Comment by ob-stripe** [comment] 2017-07-18 12:47
@Grafikart The problem is that sources are first-order API resources, while cards & bank accounts are not (i.e. you can retrieve the former with just their ID, while you need to retrieve the latter through the customer object to which they are attached). This is how the API itself is designed and is not something that can be fixed in the client libraries.

If you are really dead-set on skipping the customer retrieval request, I'd suggest something similar to what @evan-stripe said. This should work with the latest version of our PHP library:

```php
$card = \Stripe\Card::constructFrom(array(
  'id' => 'card_...',
  'customer' => 'cus_...'
), array());
$card->refresh();
```

It's definitely a bit hackish, but it works.

I suppose we could add some static methods on customer objects so you could do something like this:

```php
$card = \Stripe\Customer::retrieveCard("cus_...", "card_...");
```

but we'd need to have a method for every combination of CRUD request vs. second-order resource types (cards and bank accounts). It's definitely doable but given that it's a fairly rare use-case I'm not sure it's worth the trouble.

**Comment by MaxInMoon** [comment] 2017-09-20 16:49
+1 for a "built-in" create card method

**Closed** 2017-10-25 00:08 UTC
Labels: future

**Comment by krishnamt** [comment] 2019-08-31 13:02
> @Grafikart You don't need to add anything as it's already supported in the library and covered in the documentation. To create a card right now you have to go through the Customer who owns it. The code looks like this:
> 
> ```
> $customer = \Stripe\Customer::retrieve("cus_XXXXX");
> $customer->sources->create(array("source" => "tok_visa"));
> ```

=========================
I have tried the same approach, but im getting 
Fatal error: Uncaught Stripe\Error\InvalidRequest: No such token: tok_visa in ApiRequestor.php

**Comment by remi-stripe** [comment] 2019-08-31 15:15
I'd recommend contacting our support team: https://support.stripe.com/contact
