### ISSUE TITLE
\lib\HTTPClient CURLOPT_HEADERFUNCTION Returning Error

### ISSUE THREAD

**Issue by rtntdeck** [stripe/stripe-php#220] opened 2016-02-04 02:09 UTC
Using PHP Version => 5.4.16

With Version 3.7.1 of stripe-php 

Returns the following error:
PHP Warning:  curl_exec(): Could not call the CURLOPT_HEADERFUNCTION in <data removed>/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 119.

If line 100 is commented out the code runs and json is returned.

One person has found this issue to be environmental - with no true detail to explain that.
http://stackoverflow.com/questions/32430652/errors-when-making-a-stripe-charge-using-custom-curl-and-php-code
{EDIT - correcting stackoverflow link}http://stackoverflow.com/questions/32834703/stripe-api-php-invalid-callback

I also run Guzzle and it works fine in both dev and test environments.

Either a code fix for CurlClient.php or a detailed solution would be appreciated.

**Comment by matthewarkin** [comment] 2016-02-04 04:47
This is a warning not an error so it sounds like you have your PHP set up so that warning are treated as errors or something. 

What version of libcurl are you running?

**Comment by rtntdeck** [comment] 2016-02-04 05:01
Libcurl version: 'version' => string '7.30.0'

Here is another "warning" in the same error sequence.  
Invalid callback 0, no array or string given in <data removed>/client/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 120

The error is that the curl is not successfully setup because of the lack of valid callback; thus, no headers are written which does cause a Fatal Error within the CurlClient.php as defined on line 176.

Line 118 - curl_setopt_array($curl, $opts); returns no $curl object
Line 119 - $rbody = curl_exec($curl); returns false because there is no $curl object.

IF line 100 is commented out Line 118 and 119 succeed and there is no Fatal Error caught by line 176.

**Comment by matthewarkin** [comment] 2016-02-04 05:04
`Invalid callback 0, no array or string given in /client/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 120`

Seems a bit odd considering there is no line of code at 120 https://github.com/stripe/stripe-php/blob/v3.7.1/lib/HttpClient/CurlClient.php#L120

**Comment by rtntdeck** [comment] 2016-02-04 05:08
You're right. That was from a test I ran where I was trying to set CURLOPT_HEADERFUNCTION on its own instead of in the array.

With the removal of that single line. Here is the "warning"
PHP Warning:  Invalid callback 0, no array or string given in /Users/tdecker/local/source/ica/ise2/client/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 119

**Comment by matthewarkin** [comment] 2016-02-04 05:24
Hmm, I'm digging into it, though `curl_setopt_array($curl, $opts);` does not ever return a curl object, it just modifies the existing one and returns true or false. If it returns false the curl object should still work, just not all its options would have been set. 

I'm also confused because you're now mentioning a Fatal Error but both things you've posted are just warnings. 

What OS are you running so I can see if I can try to reproduce it?

**Comment by rtntdeck** [comment] 2016-02-04 05:33
Thanks for digging in to it.  Following is the entire sequence with the fatal error that flows from the 2 warnings. I'm on OSX 10.11.3

When the following line is commented out there are no errors or warnings.
$opts[CURLOPT_HEADERFUNCTION] = $headerCallback;

I don't use Closures at all in PHP but my theory is that it has to do with the way $headerCallback is defined.
See...http://stackoverflow.com/questions/6482068/curl-setoptch-curlopt-headerfunction-arraythis-readheader-not-working


[03-Feb-2016 23:06:10 America/Chicago] PHP Warning:  Invalid callback 0, no array or string given in <data removed>vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 119
[03-Feb-2016 23:06:10 America/Chicago] PHP Stack trace:
[03-Feb-2016 23:06:10 America/Chicago] PHP   1. {main}() <data removed>public/index.php:0
[03-Feb-2016 23:06:10 America/Chicago] PHP   2. include_once() <data removed>public/index.php:28
<data removed>
[03-Feb-2016 23:06:10 America/Chicago] PHP   9. Stripe\Customer::create() <data removed>controllers/core/StripeHandler.php:128
[03-Feb-2016 23:06:10 America/Chicago] PHP  10. Stripe\ApiResource::_create() <data removed>vendor/stripe/stripe-php/lib/Customer.php:37
[03-Feb-2016 23:06:10 America/Chicago] PHP  11. Stripe\ApiResource::_staticRequest() <data removed>vendor/stripe/stripe-php/lib/ApiResource.php:142
[03-Feb-2016 23:06:10 America/Chicago] PHP  12. Stripe\ApiRequestor->request() <data removed>vendor/stripe/stripe-php/lib/ApiResource.php:108
[03-Feb-2016 23:06:10 America/Chicago] PHP  13. Stripe\ApiRequestor->_requestRaw() <data removed>vendor/stripe/stripe-php/lib/ApiRequestor.php:59
[03-Feb-2016 23:06:10 America/Chicago] PHP  14. Stripe\HttpClient\CurlClient->request() <data removed>vendor/stripe/stripe-php/lib/ApiRequestor.php:179
[03-Feb-2016 23:06:10 America/Chicago] PHP  15. curl_exec() <data removed>vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php:119
[03-Feb-2016 23:06:10 America/Chicago] PHP Warning:  curl_exec(): Could not call the CURLOPT_HEADERFUNCTION in <data removed>vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 119
[03-Feb-2016 23:06:10 America/Chicago] PHP Stack trace:
[03-Feb-2016 23:06:10 America/Chicago] PHP   1. {main}() <data removed>public/index.php:0
[03-Feb-2016 23:06:10 America/Chicago] PHP   2. include_once() <data removed>public/index.php:28
<data removed>
[03-Feb-2016 23:06:10 America/Chicago] PHP   8. Client\Core\StripeHandler::subscribeUser() <data removed>views/Subscription.php:41
[03-Feb-2016 23:06:10 America/Chicago] PHP   9. Stripe\Customer::create() <data removed>controllers/core/StripeHandler.php:128
[03-Feb-2016 23:06:10 America/Chicago] PHP  10. Stripe\ApiResource::_create() <data removed>vendor/stripe/stripe-php/lib/Customer.php:37
[03-Feb-2016 23:06:10 America/Chicago] PHP  11. Stripe\ApiResource::_staticRequest() <data removed>vendor/stripe/stripe-php/lib/ApiResource.php:142
[03-Feb-2016 23:06:10 America/Chicago] PHP  12. Stripe\ApiRequestor->request() <data removed>vendor/stripe/stripe-php/lib/ApiResource.php:108
[03-Feb-2016 23:06:10 America/Chicago] PHP  13. Stripe\ApiRequestor->_requestRaw() <data removed>vendor/stripe/stripe-php/lib/ApiRequestor.php:59
[03-Feb-2016 23:06:10 America/Chicago] PHP  14. Stripe\HttpClient\CurlClient->request() <data removed>vendor/stripe/stripe-php/lib/ApiRequestor.php:179
[03-Feb-2016 23:06:10 America/Chicago] PHP  15. curl_exec() <data removed>vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php:119
[03-Feb-2016 23:06:10 America/Chicago] PHP Fatal error:  Uncaught exception 'Stripe\Error\ApiConnection' with message 'Unexpected error communicating with Stripe.  If this problem persists, let us know at support@stripe.com.

(Network error [errno 23]: Failed writing header)' in <data removed>vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php:182
Stack trace:
#0 <data removed>vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php(144): Stripe\HttpClient\CurlClient->handleCurlError('https://api.str...', 23, 'Failed writing ...')
#1 <data removed>vendor/stripe/stripe-php/lib/ApiRequestor.php(179): Stripe\HttpClient\CurlClient->request('post', 'https://api.str...', Array, Array, false)
#2 <data removed>vendor/stripe/stripe-php/lib/ApiRequestor.php(59): Stripe\ApiRequestor->_requestRaw('post', '/v1/customers', Array, Array)
#3 <data removed>vendor/stripe/stripe-php/lib/ApiResource.php(108): Stripe\ApiRequestor->reques in <data removed>vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 182

**Comment by rtntdeck** [comment] 2016-02-04 05:36
Also realized I left the wrong link to stackoverflow in the first post.

Here it is.
http://stackoverflow.com/questions/32834703/stripe-api-php-invalid-callback

**Comment by brandur** [comment] 2016-02-04 13:36
Hi @rtntdeck, thanks for logging this! I'm sorry to hear that you're having trouble here.

I guess we could change the use of `CURLOPT_HEADERFUNCTION` in the library to a non-closure version, but based on your provided SO link and the fact that we've never had this one reported by anyone else, it seems like the problem might lie in an unusual PHP compilation on your local machine. Is there any chance you could try a different release and see whether the problem persists?

It might also be worth trying to locally move that closure to a class member function and then invoking it with something like:

``` php
curl_setopt($ch, CURLOPT_HEADERFUNCTION, array(self,'readHeader'));
```

If that doesn't work, see if a similar idea but with `readHeader` in the global namespace will work:

``` php
curl_setopt($ch, CURLOPT_HEADERFUNCTION, 'readHeader');
```

Let us know! Thanks.

**Comment by rtntdeck** [comment] 2016-02-04 14:37
With no environment changes I did the following.

I pulled the readHeader function up as its own method within the class and everything works fine. No warnings or Errors and $this->rHeaders is populated at the end of a call.

In doing so it was also required to make rHeaders a class property and change some references to $this->rHeaders ($this since it is not a static class or set of functions).

Adding this line made the customHeaderCallback get inlined with Curl correctly.(again $this because its not a static class)
$opts[CURLOPT_HEADERFUNCTION] = array($this, 'customHeaderCallback');

    public function customHeaderCallback ($curl, $header_line){
        if (strpos($header_line, ":") === false) {
                return strlen($header_line);
            }
            list($key, $value) = explode(":", trim($header_line), 2);
            //$rheaders[trim($key)] = trim($value);
            $this->rheaders[trim($key)] = trim($value);
            return strlen($header_line);
    }

As for reasons why no one else has come across this I can only guess. A)PHP community isn't yet using stripe-php 3.* (which is when CurlClient was introduced). B)From what I can tell most PHP folks have coded their own Curl wrappers thus may never hit this code. Purely guesses though.

**Comment by brandur** [comment] 2016-02-05 15:01
> I pulled the readHeader function up as its own method within the class and everything works fine. No warnings or Errors and $this->rheaders is populated at the end of a call.
>
> In doing so it was also required to make rheaders a class property and change some references to $this->rheaders ($this since it is not a static class or set of functions).

Good to hear that you got it fixed!

It's probably overly academic to be talking about things like thread-safety in a language like PHP (while technically supporting threads, they're probably not widely used), but the only trouble here is that your request function is no longer re-entrant because you're now storing data in the instance. i.e. Two request calls made around the same time will conflict with each other.

> As for reasons why no one else has come across this I can only guess. A)PHP community isn't yet using stripe-php 3.* (which is when CurlClient was introduced). B)From what I can tell most PHP folks have coded their own Curl wrappers thus may never hit this code. Purely guesses though.

Ah, maybe! I guess the only thing to consider is that looking at the [SO issue that you linked above](https://stackoverflow.com/questions/32834703/stripe-api-php-invalid-callback) it seems like the user there was able to get things working by moving to a different build of PHP in their server environment. I still kind of suspect that some anomalous builds of PHP might be the culprit here.

**Comment by brandur** [comment] 2016-06-04 22:51
Closing this one out for now.

**Closed by brandur** 2016-06-04 22:51 UTC

**Comment by axis80** [comment] 2016-08-02 19:34
I realize that this issue is closed.  I simply wanted to report that I experienced it also.  PHP version 5.4.38, Curl 7.38.0, OpenSSL 1.0.1e, cPanel hosting control panel.

I am unable to upgrade any of the above components as this is a client's hosting account that is not under my control.   I've tried various permutations of rtntdeck's fix with no luck.  I've pretty much exhausted the limits of my abilities in debugging it, so I'm afraid I don't have much more to offer than this "me too" report.

**Comment by rtntdeck** [comment] 2016-08-02 23:46
@axis80 here is what I have done that I am still using in production.

All changes are for the stripe/stripe-php/lib/HttpClient/CurlClient.php file.
```
    //Add this as a class property
    public $rheaders = array();


   //Add this class method
    public function customHeaderCallback ($curl, $header_line){
        if (strpos($header_line, ":") === false) {
                return strlen($header_line);
            }
            list($key, $value) = explode(":", trim($header_line), 2);
            $this->rheaders[trim($key)] = trim($value);
            return strlen($header_line);
    }


     //Original line directly below
     //$opts[CURLOPT_HEADERFUNCTION] = $headerCallback;

     //This is the changed line.
     $opts[CURLOPT_HEADERFUNCTION] = array($this, 'customHeaderCallback');
```
