### ISSUE TITLE
New php api has issues "Cannot charge a customer that has no active card"

### ISSUE THREAD

**Issue by wangfei800** [stripe/stripe-php#477] opened 2018-05-20 20:55 UTC
I started to use Stripe, and setup the account, and did some testing of payment, it works fine.
However, yesterday, after I run composer update on server, the payment api is broken now, I got exception with message "Cannot charge a customer that has no active card".

I am running on testing key now.
Thanks

**Comment by remi-stripe** [comment] 2018-05-20 21:11
This is unlikely to be a bug with the PHP library. This error simply means that you are trying to charge a customer but you never saved a card on that customer first.

I'd recommend looking into your code and adding logs to confirm if you've properly retrieved a card token and added it to the customer first.

I'm closing as this is not a bug and you can reach out to our support team for help otherwise here: https://support.stripe.com/email

**Closed by remi-stripe** 2018-05-20 21:11 UTC
