### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by tin-cat** [stripe/stripe-php#1185] opened 2021-10-02 18:22 UTC
As PHP 8 gradually becomes the new standard for PHP-based applications, more and more developers and server environments are welcoming the performance improvements of JIT and the many new tools that make PHP development easier and powerful as ever.

Unfortunately stripe-php is not compatible yet with PHP 8, specially suffering from issues related to certain deprecated function usages and type constrains like https://github.com/stripe/stripe-php/issues/1125

I'm sure many developers would love to be able to use this library in their new PHP 8-based environments. Being Stripe so widely used, this would also encourage more developers to adopt PHP 8 in their projects.

Thank you.

**Comment by remi-stripe** [comment] 2021-10-02 18:33
@tin-cat Thanks for the report! We'll see if we can work on PHP8 compatibility and then add it to our test suite, there shouldn't be too many drastic changes in the library and we agree we should be supporting the latest major versions of all languages

**Comment by tin-cat** [comment] 2021-10-02 18:38
That would be fantastic! So much thanks for such a great work!

**Comment by MatanYadaev** [comment] 2021-11-28 14:17
@remi-stripe PHP 8.1 is out. Any progress with that?

**Comment by BenMorel** [comment] 2021-12-04 17:35
Stripe is already 1 year behind. Could you please add support for both PHP 8.0 and 8.1 ASAP? Thank you.

**Comment by richardm-stripe** [comment] 2021-12-06 22:49
Hello @tin-cat, @BenMorel, and @MatanYadaev 

As of [v7.104.0](https://github.com/stripe/stripe-php/releases/tag/v7.104.0) we are now running our test suites and static analyzers on PHP 8 and PHP 8.1. Were there any particular incompatibilities that you have noticed? I've looked into https://github.com/stripe/stripe-php/issues/1125 and cannot reproduce it.

**Comment by BenMorel** [comment] 2021-12-06 23:39
@richardm-stripe Works fine for me (no more deprecation warnings) with v7.105.0, thanks!

**Comment by richardm-stripe** [comment] 2021-12-07 00:46
Thank you @BenMorel. 

I am closing this issue. This library now officially supports PHP 8.1. 

We already have a large number of users who appear to have successfully been using PHP8 in production and a sizeable number that have adopted PHP8.1 despite the deprecation warnings.

Any further compatibility issues will be treated as urgent bugs.

Thank you all!

**Closed by richardm-stripe** 2021-12-07 00:46 UTC
