### ISSUE TITLE
Unable to get HTTP_STRIPE_SIGNATURE

### ISSUE THREAD

**Issue by benjarn374** [stripe/stripe-php#697] opened 2019-08-19 15:14 UTC
Hello, 
I dont know if its a server-side problem but in webhook script the $_SERVER['HTTP_STRIPE_SIGNATURE']; is always empty ?
And i cant perform verification and get "Invalid signature"
Somebody can help me ?

**Comment by remi-stripe** [comment] 2019-08-19 15:20
@benjarn374 Many things can cause this on your side. Your framework might temper or remove headers, you might not have revealed the secret of the webhook endpoint, you might not test properly with a real event sent from your account, etc.

I'd recommend reaching out to our support team https://support.stripe.com/contact and provide all information (exact event, your code, the raw dump of the data we sent you, etc) and they should be able to help.

Closing the issue here as it's not a bug with our libraries and more a problem with the integration.

**Closed by remi-stripe** 2019-08-19 15:20 UTC
