### ISSUE TITLE
\Stripe\Customer::save() throws an exception after migration to 6.0

### ISSUE THREAD

**Issue by idealogica** [stripe/stripe-php#451] opened 2018-02-26 16:26 UTC
Hello,
For stripe-php v6.0.0 \Exception is thrown on \Stripe\Customer::save() call with the message: "token is not supported". The same code works well with stripe-php v5.9.0. 
The code is:
```php
$params = [
    'card' => [
        'number'    => $ccNumber,
        'exp_month' => $expireMonth,
        'exp_year'  => $expireYear,
    ]
];
if ($cvc) {
    $params['card']['cvc'] = $cvc;
}
if ($cardHolder) {
    $params['card']['name'] = $cardHolder;
}
$ccToken = \Stripe\Token::create($params);
$Customer = \Stripe\Customer::retrieve($customerId);
$Customer->source = $ccToken;
$Customer->save();
```
PHP 7.2.2

**Comment by ob-stripe** [comment] 2018-02-26 16:46
You're passing a full token object as the `source` parameter instead of just the ID. You can fix your code like this:
```php
$Customer->source = $ccToken->id;
$Customer->save();
```

Closing this issue because I don't think the previous behavior was intended and something we actually want to support.

**Closed by ob-stripe** 2018-02-26 16:46 UTC

**Comment by idealogica** [comment] 2018-02-28 13:57
Thank you for the solution!
