### ISSUE TITLE
Stripe-PHP lib segfaults PHP-FPM on PHP 8.1

### ISSUE THREAD

**Issue by levelsio** [stripe/stripe-php#1430] opened 2023-01-28 18:59 UTC
### Describe the bug

My Stripe webhook script started giving 502 Bad Gateway errors. So I checked and I was able to isolate the problem to the Stripe code. Any time I'd use the Stripe lib it would SEGFAULT the PHP-FPM daemon and there wouldn't be a PHP error even with error_reporting on. I didn't change any of the code so it's all quite random. 

The only fix I could do is switch my PHP-FPM daemon from PHP 8.1 to PHP 7.3 and suddenly everything started working. Stripe has really good engineering so it's probably my bug somewhere but I wanted to report it anyway in case someone else had the same issue.

It was quite annoying because for a week on my site interiorai.com people would sign up but wouldn't get user accounts cause webhooks didn't work etc.

### To Reproduce

Use PHP 8.1
With Stripe-PHP SDK
Get PHP-FPM segfaulting

### Expected behavior

Use PHP 8.1
WIth Stripe-PHP SDK
It works

### Code snippets

```PHP
\Stripe\Stripe::setApiKey(
	$config['stripe']['general']['secret']
);

$event = \Stripe\Webhook::constructEvent(
$payload, $sig_header, $endpoint_secret
);
```

### OS

Ubuntu

### PHP version

PHP 8.1

### Library version

stripe/stripe-php v9.9.0  

### API version

2022-11-15

### Additional context

2023/01/28 18:12:13 [error] 21122#21122: *99211595 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 54.187.174.169, server: interiorai.com, request: "POST /stripe_webhook?key=XXXXXXXXXXXXXX HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm.sock:", host: "interiorai.com"
2023/01/28 18:12:13 [error] 21122#21122: *99210973 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 54.187.174.169, server: interiorai.com, request: "POST /stripe_webhook?key=XXXXXXXXXXXXXX HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm.sock:", host: "interiorai.com"
2023/01/28 18:15:52 [error] 21122#21122: *99215789 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 54.187.174.169, server: interiorai.com, request: "POST /stripe_webhook?key=XXXXXXXXXXXXXX HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm.sock:", host: "interiorai.com"
2023/01/28 18:16:33 [error] 21122#21122: *99216632 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 54.187.174.169, server: interiorai.com, request: "POST /stripe_webhook?key=XXXXXXXXXXXXXX HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm.sock:", host: "interiorai.com"
2023/01/28 18:26:30 [error] 21122#21122: *99226841 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 54.187.205.235, server: interiorai.com, request: "POST /stripe_webhook?key=XXXXXXXXXXXXXX HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm.sock:", host: "interiorai.com"
2023/01/28 18:31:26 [error] 32151#32151: *99231611 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 54.187.174.169, server: interiorai.com, request: "POST /stripe_webhook?key=XXXXXXXXXXXXXX HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm.sock:", host: "interiorai.com"

**Comment by richardm-stripe** [comment] 2023-01-28 20:15
Hello @levelsio, thank you for reporting this. Trying to put together a plan to reproduce/debug this.

Given the involvement of `PHP-FPM` I suspect the segfault may be happening before any `stripe-php` code is triggered and so this isn't something we could fix by patching the library -- the problem may be a bad interaction between the new PHP-FPM version and something peculiar about the HTTP/TCP nature of the webhook requests that Stripe is sending to your servers. 

I think it's a good idea to leave this ticket open so anybody else encountering this can chime in, but I may need to forward you to [contact Stripe Support](https://support.stripe.com/contact) and open a ticket. Our network/traffic teams are probably the best equipped to debug this but they don't have a presence on the public Github.

Would you be willing to provide the timezone that your log entries `2023/01/28 18:31:26` are in, and also, do you have a description of the timeframes you saw this issue? If it was intermittent and caused by a network change on our end, this could help correlate it.

**Comment by levelsio** [comment] 2023-01-28 20:59
Thanks a lot @richardm-stripe! Timezone is UTC. It has been happening since 2023-01-22 to 2023-01-28 (when I switched back to PHP 7.3). Feel free to look into my account to debug it. As always it's probably MY bug or something weird on my server because I haven't seen anyone else with this problem this week. Then again I may be the first.

**Comment by levelsio** [comment] 2023-01-28 21:03
Interesting one possible other report:

https://twitter.com/pmontp19/status/1619440306533044224

**Comment by localheinz** [comment] 2023-01-28 22:12
@levelsio @richardm-stripe 

Perhaps related to https://github.com/php/php-src/issues/7817?

**Comment by pakrym-stripe** [comment] 2023-06-14 14:44
I'm going to close the issue as it seems to be related to PHP JIT bugs. Stripe library is not doing anything unsafe enough to segfault the interpreter.

**Closed by pakrym-stripe** 2023-06-14 14:44 UTC
Labels: bug
