### ISSUE TITLE
Incorrect serizlization to objects/arrays

### ISSUE THREAD

**Issue by AlexNodex** [stripe/stripe-php#684] opened 2019-07-30 13:23 UTC
The library does not serialize input arrays properly and instead attempts to convert them to a json object with erroneous keys.

```
$payload = [
      "url" => "<omitted>",
      "enabled_events"=>[
        "payment_intent.succeeded",
        "payment_intent.failed"
      ]
    ];

$response = \Stripe\WebhookEndpoint::create($payload);
// this yealds an error that it does not contain a correct set of `enabled_events`
```
The code above lifted right from the documentation.

A quick look at the logs inside the dashboard and we can see the payload the stripe library sent...

```
{
  "url": "<omitted>",
  "enabled_events": {
    "0": "payment_intent.succeeded",
    "1": "payment_intent.failed"
  }
}
```
As you can see it's converted a basic array in to a json object with keys.

**Comment by AlexNodex** [comment] 2019-07-30 13:39
The line that causes it is here

https://github.com/stripe/stripe-php/blob/9c22ffab790ef4dae0f371929de50e8b53c9ec8d/lib/ApiRequestor.php#L86

Obviously it's blindly adding the key, I guess it needs checking if it's a string key and add it as a string else don't but I don't know what it will break in the rest of the API....

**Comment by ob-stripe** [comment] 2019-07-30 13:50
This is expected, all arrays are encoded as integer-indexed maps, and the API knows how to convert those back into arrays.

The request fails because `payment_intent.failed` is not a valid event type, it should be [`payment_intent.payment_failed`](https://stripe.com/docs/api/events/types#event_types-payment_intent.payment_failed) instead.

Closing because this is not a bug with the library, but if you can tell me where in the docs you saw that example, I'll relay it and make sure it's fixed.

**Closed by ob-stripe** 2019-07-30 13:50 UTC
