### ISSUE TITLE
drupal issues

### ISSUE THREAD

**Issue by babitabhandari** [stripe/stripe-php#247] opened 2016-04-15 05:35 UTC
I have installed php library in libraries folder in drupal.Now You just tell me how to fetch php-library  in libraries folder in drupal and how i include file of php-library init.php file  in module folder in drupal.If i use require_once it cause  fatal  error.Please give me guide how to use require_once(); in drupal.

**Comment by remistr** [comment] 2016-04-15 06:20
Closing as duplicate of https://github.com/stripe/stripe-php/issues/245

**Closed by remistr** 2016-04-15 06:20 UTC

**Comment by babitabhandari** [comment] 2016-04-15 07:42
I have solved this issue.Thanx for help me.Actually the main problem was about require_once and i have solved it.
