### ISSUE TITLE
Bug in coupons

### ISSUE THREAD

**Issue by bastien70** [stripe/stripe-php#1146] opened 2021-06-25 15:31 UTC
Symfony 5.3
PHP 8.0

I don't know if it's from Stripe-PHP or the API itself, but there seems to be a bug with the coupons.

When I checkout with a promotional code (open to everyone, and not intended for a specific customer), I still get the following error:

> "This promotion code cannot be redeemed because the associated customer has prior transactions."

While this is the 1st time that this code has been used, and the customer has not made any order before

And if I look in the creation logs of my promotional code, you can see that it is not associated with any customer : 

```
{
  "object": {
    "id": "promo_1J6EtmGgCQgXBLKXJitCTNmt",
    "object": "promotion_code",
    "active": true,
    "code": "aK3dfYZqVV",
    "coupon": {
      "id": "0DIUoKSl",
      "object": "coupon",
      "amount_off": 3000,
      "created": 1624627005,
      "currency": "eur",
      "duration": "once",
      "duration_in_months": null,
      "livemode": false,
      "max_redemptions": null,
      "metadata": {
        "sponsorship": "true",
        "minAmount": "250",
        "discountTypeForGodson": "amount",
        "amountForGodson": "30"
      },
      "name": "Réduction en tant que filleul",
      "percent_off": null,
      "redeem_by": null,
      "times_redeemed": 0,
      "valid": true
    },
    "created": 1624627006,
    "customer": null,
    "expires_at": null,
    "livemode": false,
    "max_redemptions": null,
    "metadata": {
    },
    "restrictions": {
      "first_time_transaction": true,
      "minimum_amount": 25000,
      "minimum_amount_currency": "eur"
    },
    "times_redeemed": 0
  }
}
```

![image](https://user-images.githubusercontent.com/53140475/123449144-ace25400-d5db-11eb-86e6-44ea06d0f3f5.png)

**Comment by remi-stripe** [comment] 2021-06-26 12:42
@bastien70 The promo code you have can only be used with a brand new customer that never had a payment before because of the way you configured it with `first_time_transaction: true`. You seem to be creating a customer, then charging them via a PaymentIntent (first transaction done) and then create a separate subscription which would charge them a second time but the promotion code is rejected as they already had a transaction.

It's likely that you didn't want to create that PaymentIntent and wanted the Subscription to be charging them since this happens automatically?

Since this is not a bug with the library itself I'm going to close this out. I recommend contacting our support team https://support.stripe.com/contact/email or talking to developers on our Discord community server: https://stripe.com/go/developer-chat

**Closed by remi-stripe** 2021-06-26 12:42 UTC
