### ISSUE TITLE
Received unknown parameter: invoicing  

### ISSUE THREAD

**Issue by YouMakeMeHappy** [stripe/stripe-php#595] opened 2019-02-08 13:45 UTC
Hello. How I can update "Send emails to" and "CC" fields in customer invoice details?

Api version: 2018-11-08
SDK version: 6.29.0

I tried:

```php
        \Stripe\Stripe::setApiKey("XXXXXXXXXXX");
        \Stripe\Stripe::setApiVersion('2018-11-08');

        $customer = Customer::update(
            "XXXXXX",
            [
                'description' => 'test update via api',
                'invoicing' => ['email_to' => ['XXXX@gmail.com'], 'email_cc' => ['XXXX+1@gmail.com']],
            ]
        );
```

And receive an error:

`Received unknown parameter: invoicing  `

I see, what in Dashboard, when update details, js send Ajax to URL: https://dashboard.stripe.com/ajax/graphql

with data:

```json
{
  "data": {
    "updateCustomer": {
      "id": "XXXX",
      "__typename": "Customer",
      "created": 1533288132,
      "deleted": false,
      "account_balance": 0,
      "currency": null,
      "description": "test update via api",
      "email": "XXXX@gmail.com",
      "invoice_prefix": "XXXX",
      "invoicing": {
        "email_to": [
          "XXXXX@gmail.com",
          "XXXXX+1@gmail.com"
        ],
        "email_cc": [
          "XXXXX+2@gmail.com"
        ],
        "__typename": "Invoicing"
      },
      "name": null,
      "phone": null,
      "address": null,
      "shipping": {
        "address": {
          "line1": "address1",
          "line2": "",
          "city": "",
          "state": "",
          "country": "US",
          "postal_code": "",
          "__typename": "Address"
        },
        "name": "",
        "phone": "",
        "__typename": "Shipping"
      },
      "subscriptions": {
        "total_count": 0,
        "__typename": "SubscriptionsList"
      },
      "tax_info": {
        "tax_id": "t",
        "type": "vat",
        "__typename": "TaxInfo"
      }
    }
  },
  "errors": null
}
```

Thanks.

**Comment by ob-stripe** [comment] 2019-02-08 14:06
Hi @YouMakeMeHappy. The `invoicing` parameter in customer update requests can only be used by the dashboard, not by regular integrations.

I'm closing this issue since this is not a bug or feature request for the PHP library. If you'd like the API to support this feature, I recommend that you write to Stripe's support at https://support.stripe.com/email and explain your usecase.

**Closed by ob-stripe** 2019-02-08 14:06 UTC

**Comment by TehNrd** [comment] 2021-09-26 21:36
Oof, I can't believe this isn't updatable through the API. This just introduced a fun manual step for us with every new customer signup. I'll be reaching out to support with my use case!
