### ISSUE TITLE
Unexpected error communicating with Stripe

### ISSUE THREAD

**Issue by jamminjames** [stripe/stripe-php#512] opened 2018-08-30 03:30 UTC
I am testing with stripe using this library, and am getting the "Unexpected error communicating with Stripe" error. I believe curl and TLS are set up correctly, so I don't know what the problem is. 

I am using my test account API keys from Stripe, and the [test form by bateller here](https://gist.github.com/bateller/154c6e5d1f6e0e53e527).

Thanks for any help!

I ran tls_test.php on the server, and got:

OS: Linux
uname: Linux dcn-colo-251-95.dcn.davis.ca.us 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64
PHP version: 7.0.27
curl version: 7.29.0
SSL version: NSS/3.34
SSL version number: 0
OPENSSL_VERSION_NUMBER: 100020bf
TLS test (default): TLS 1.2
TLS test (TLS_v1): TLS 1.2
TLS test (TLS_v1_2): TLS 1.2

**Comment by jamminjames** [comment] 2018-08-30 04:44
Follow up. When I use the line:
`\Stripe\Stripe::setVerifySslCerts(false);`
Stripe reports on the dashboard that a successful payment was made, even though on my test form I get a "Your payment failed" error after submitting.  So, there's something about the SSL cert it doesn't like, and I am looking into that. It should be fine, as shown above, and I checked the expiration, which is not until March 2019, so it's odd.

Also, Stripe tries to send a Webhook message back, but the dashboard shows the status is stuck at "500 Pending." I've double-checked the Webhook setup on the site, and it seems fine, using the correct test secret key, etc.

**Comment by remi-stripe** [comment] 2018-08-30 12:07
@jamminjames The 500 on the webhook just means that your code has a bug somewhere and just crashes. I'd recommend double checking the logs to confirm what's going on.

I'm going to close this out since it seems specific to your setup and not a bug in the library but you can talk to our support team directly if you still experience issues: https://support.stripe.com/email

**Closed by remi-stripe** 2018-08-30 12:07 UTC
