### ISSUE TITLE
PHP 7 Incompatibilities: Usage of list()

### ISSUE THREAD

**Issue by strgg** [stripe/stripe-php#322] opened 2017-02-11 21:27 UTC
Reference:
http://php.net/manual/en/function.list.php
View WARNINGS (in red) and CHANGELOG ... to check the PHP-7 incompatibilities!

Problem in stripe-PHP: 
Fatal Server Error

Reason:
Usage of list when one of the variables is empty (Invalid in PHP-7)
Not appropriate usage of try/catch !!! (for coding standards change for future)

the use of list() is incompatible regarding PHP-7 in the stripe-php library (it only affects at rare errors , but still). I debugged 2 hours fixing the code. it's a sign of complete incompetence of stripe-php and its users and contributers that those incomptabilities have not been raised to awareness and fixed yet, sorry :) .... to be found easily in ..lib/ApiResource.php ... for example
```
line 120
list($response, $opts->apiKey) = $requestor->request($method, $url, $params, $opts->headers); 
```
$response is **_empty_** (in PHP-7 invalid)
_Order inversed_ 

Reproduction:
Set ON Error in stripe.php or index.php: 
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
 
One of the errors can be reproduced if you switch to testing/sandbox mode. Then input a valid real world credit card  or just alter the last number of a testing card (instead of the testing credit cards stripe provides you with). It throws a Fatal Server Error which can be traced back to the use of ->  list()

Examples of Errors: (All those errors cause a "Fatal Server Error" and therefore don't display any Error to the customer!!
---------------------------------------------------------------
Caused by:
CC: 4242 4242 4242 4242 **42**
Expiration Month: 12 Year: 18 
CV: 222
Reason: added 2 additional Numbers -> No valid Testing card

<br />
<b>Fatal error</b>:  Uncaught Stripe\Error\Card: Your card was declined. Your request was in test mode, but used a non test card. For a list of valid test cards, visit: https://stripe.com/docs/testing. in system/library/stripe-php/ApiRequestor.php:114 from API request 'req_A9OniT46tsIA3Q'
Stack trace:

#0 system/library/stripe-php/ApiRequestor.php(266): Stripe\ApiRequestor-&gt;handleApiError('{\n  &quot;error&quot;: {\n...', 402, Array, Array)
#1 system/library/stripe-php/ApiRequestor.php(65): Stripe\ApiRequestor-&gt;_interpretResponse('{\n  &quot;error&quot;: {\n...', 402, Array)
#2 system/library/stripe-php/ApiResource.php(120): Stripe\ApiRequestor-&gt;request('post', '/v1/customers/c...', Array, Array)
#3 library/stripe-php/ApiResource.php(111): Stripe\ApiResource::_staticRequest('post', '/v1/customers/c...', Array, Object(Stripe\Util\RequestOptions))
#4 system/libra in <b>system/library/stripe-php/ApiRequestor.php</b> on line <b>114</b><br />

----------------------------------------------
Caused by: 
CC: 4242 4242 4242 4242
Expiration Month: 12 Year: **2018** 
CV: 222
Reason: 2018 instead of 18

<b>Fatal error</b>:  Uncaught Stripe\Error\InvalidRequest: Invalid positive integer in system/library/stripe-php/ApiRequestor.php:110 from API request 'req_A9ObsgSkTAhCvY'
Stack trace:
#0 system/library/stripe-php/ApiRequestor.php(266): Stripe\ApiRequestor-&gt;handleApiError('{\n  &quot;error&quot;: {\n...', 400, Array, Array)
#1 system/library/stripe-php/ApiRequestor.php(65): Stripe\ApiRequestor-&gt;_interpretResponse('{\n  &quot;error&quot;: {\n...', 400, Array)
#2 system/library/stripe-php/ApiResource.php(120): Stripe\ApiRequestor-&gt;request('post', '/v1/charges', Array, Array)
#3 system/library/stripe-php/ApiResource.php(161): Stripe\ApiResource::_staticRequest('post', '/v1/charges', Array, NULL)
#4 system/library/stripe-php/Charge.php(73): Stripe\ApiResource::_create(Array, NULL)
#5 system/library/stripe-php/ApiRequestor.php</b> on line <b>110</b><br />

**Comment by ob-stripe** [comment] 2017-02-12 01:54
Hi @strgg. These errors are not caused by the usage of `list()` in PHP 7.

When the API returns an error, the PHP library translates these errors as exceptions. It is up to you to catch these exceptions and handle them appropriately. For more information, please refer to the following paragraphs of the API reference:
- [Errors](https://stripe.com/docs/api/php#errors)
- [Handling errors](https://stripe.com/docs/api/php#handling-errors)

In the case of the first error you mentioned, you provided a valid number (some card numbers can have 18 digits) that is not a [test number](https://stripe.com/docs/testing#cards), so the API correctly returned a `card_error` with the following message: "Your card was declined. Your request was in test mode, but used a non test card. For a list of valid test cards, visit: https://stripe.com/docs/testing."

In the case of the second error, it was not caused by the expiry year having 4 digits (as the API accepts both 2 and 4 digits numbers for the [expiry year](https://stripe.com/docs/api/php#create_card-source-exp_year)), but rather because you passed `0` for the [`amount`](https://stripe.com/docs/api/php#create_charge-amount) parameter of your charge creation request.

As this is not an issue with the PHP library, I'm going to close the issue. If you need more help using Stripe's API, please reach out to support at https://support.stripe.com/email.

**Closed by ob-stripe** 2017-02-12 01:54 UTC

**Comment by strgg** [comment] 2017-02-12 09:58
@ob-stripe 
I don't complain about the API (Server Stripe) but how the code in stripe-PHP handles the response and lacks correct exception handling. When you echo $response in ...lib/ApiResource.php on line 120 AFTER reproducing an error (Testmode, non-test-creditcard), then you will see an empty value ... which ... is not allowed in PHP-7 anymore (see CHANGELOG on the list page at php.net).

The error occurs in stripe-php's library and not in ours (Magento).. thanks for your time

**Comment by ob-stripe** [comment] 2017-02-12 13:32
If an error is returned by the API, the `list($response, $opts->apiKey) = $requestor->request(...)` assignment is never executed because an exception is raised inside `$requestor->request(...)`, before any values are returned.

This is by design: the [`handleApiError()`](https://github.com/stripe/stripe-php/blob/5bab8a11a727ed9c89b22ee1fa7745e010c9f023/lib/ApiRequestor.php#L87) method is called when the API returns an error, and explicitly raises an exception.

I have also tested your examples with PHP 7.0.15 and observed the expected behavior: a `\Stripe\Error\Exception` of the appropriate subclass is raised (i.e. what you described in your first post).

Looking at the code of the [`request()`](https://github.com/stripe/stripe-php/blob/5bab8a11a727ed9c89b22ee1fa7745e010c9f023/lib/ApiRequestor.php#L55-L68) method, I don't see how it would be possible for the method to not raise an exception and return a `null` value in the first element of the returned array. Could you provide code for reproducing this case?
