### ISSUE TITLE
Network error [errno 55]

### ISSUE THREAD

**Issue by Tushar-Kanvinde** [stripe/stripe-php#581] opened 2019-01-21 10:55 UTC
I am trying to make a charge in stripe and I am getting the following error

PHP Fatal error:  Uncaught Stripe\\Error\\ApiConnection: Unexpected error communicating with Stripe.  If this problem persists, let us know at support@stripe.com.
(Network error [errno 55]: Failed sending HTTP POST request) in /var/business/app/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php:317

Stack trace:
#0 /var/business/app/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php(274): Stripe\\HttpClient\\CurlClient->handleCurlError('https://api.str...', 55, 'Failed sending ...', 0)
#1 /var/business/app/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php(234): Stripe\\HttpClient\\CurlClient->executeRequestWithRetries(Array, 'https://api.str...')
#2 /var/business/app/vendor/stripe/stripe-php/lib/ApiRequestor.php(399): Stripe\\HttpClient\\CurlClient->request('post', 'https://api.str...', Array, Array, false)
#3 /var/business/app/vendor/stripe/stripe-php/lib/ApiRequestor.php(125): Stripe\\ApiRequestor->_requestRaw('post', '/v1/charges', Array, Array)
#4 /var/business/app/vendor/stripe/stripe-php/lib/ApiOperations/Request.php in /var/business/app/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 317, 

the command I use is

$reqdata = [
    "amount" => $amount * 100,
    "currency" => $currency,
    "source" => $token, // obtained with Stripe.js
    "description" => $narration
];
\Stripe\Stripe::setApiKey(stripe_secret_key);
$response = \Stripe\Charge::create($reqdata, [
            "idempotency_key" => $guid,
        ]);

My server settings are

OS: Linux
uname: Linux rtac-india 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64
PHP version: 7.0.33-0+deb9u1
curl version: 7.52.1
SSL version: OpenSSL/1.0.2q
SSL version number: 0
OPENSSL_VERSION_NUMBER: 101000af
TLS test (default): TLS 1.2
TLS test (TLS_v1): TLS 1.2
TLS test (TLS_v1_2): TLS 1.2

Thanks

**Comment by ob-stripe** [comment] 2019-01-21 11:42
Hi @Tushar-Kanvinde. In most cases such network errors are caused by connectivity issues between your server and Stripe's API, not by problems in the PHP library itself.

I would recommend running the reachability test script from https://github.com/stripe/stripe-reachability on your server and sending the results to Stripe's support at https://support.stripe.com/email, along with the information you shared in this post. You should also ask your network administrator or hosting provider to check for network issues between your server and `api.stripe.com`.

Closing the issue, but feel free to reply if you have reason to believe this is actually a bug with the library.

**Closed by ob-stripe** 2019-01-21 11:42 UTC
