### ISSUE TITLE
Get an exception "exception 'Stripe_AuthenticationError' with message 'Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later."

### ISSUE THREAD

**Issue by bswscube** [stripe/stripe-php#307] opened 2016-11-02 05:40 UTC
I am using below code in PHP

```php
require_once('Stripe/lib/Stripe.php');
Stripe::setApiKey("KEY");

$charge = Stripe_Charge::create(array(
  "amount" => 1500,
  "currency" => "usd",
  "card" => $_POST['stripeToken'],
  "description" => "Charge."
));

//send the file, this line will be reached if no error was thrown above
echo "<h1>Your payment has been completed. We will send you the Facebook Login code in a minute.</h1>";

echo $_POST['stripeToken'];
//you can send the file to this email:
echo $_POST['stripeEmail'];
```

When i am running above script i am getting an exception i.e "exception 'Stripe_AuthenticationError' with message 'Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later."   Please help me out to solve this issue as soon as possible. Currently i am working at local environment.

Thanks

**Comment by ob-stripe** [comment] 2016-11-02 08:20
Hi @bswscube. Stripe now requires that all requests to our API use TLS 1.2 or later. You can read more about this here: https://stripe.com/blog/upgrading-tls.

As this is a problem with your own server and not a bug with the PHP library, I'm going to close the issue. You should reach out to Stripe support using the form at https://support.stripe.com/email to receive help about this issue, but in a nutshell, you'll likely need to upgrade the software packages for PHP, curl and OpenSSL on your server.

**Closed by ob-stripe** 2016-11-02 08:20 UTC
