### ISSUE TITLE
stripeToken : possible fraud / amount change 

### ISSUE THREAD

**Issue by B-Poignant** [stripe/stripe-php#345] opened 2017-05-03 08:39 UTC
Hi,

I make some test to implement stripe on my website and i found something strange, with version 4.9.0, i can create a token for a payment to 20€ and take any amount when i make Stripe\Charge::create call.

Here an example : 

```
$stripe = array(
  "secret_key"      => "my_sk_key",
  "publishable_key" => "my_pk_key"
);

require_once('./stripe-php-4.9.0/init.php');


try {
	\Stripe\Stripe::setApiKey($stripe['secret_key']);

	if(isset($_POST['stripeToken'])){
		$token  = $_POST['stripeToken'];

		$customer = \Stripe\Customer::create(array(
			'email' => 'customer@example.com',
			'source'  => $token
		));

		$charge = \Stripe\Charge::create(array(
			'customer' => $customer->id,
			'amount'   => 5000,
			'currency' => 'eur'
		));

		echo '<h1>Successfully charged $20.00!</h1>';
	}
} catch(\Stripe\Error\Card $e) {
	  // Since it's a decline, \Stripe\Error\Card will be caught
	  $body = $e->getJsonBody();
	  $err  = $body['error'];

	  print('Status is:' . $e->getHttpStatus() . "\n");
	  print('Type is:' . $err['type'] . "\n");
	  print('Code is:' . $err['code'] . "\n");
	  // param is '' in this case
	  print('Param is:' . $err['param'] . "\n");
	  print('Message is:' . $err['message'] . "\n");
} catch (\Stripe\Error\RateLimit $e) {
  echo 'Too many requests made to the API too quickly';
} catch (\Stripe\Error\InvalidRequest $e) {
   echo ' Invalid parameters were supplied to Stripe\'s API';
} catch (\Stripe\Error\Authentication $e) {
   echo ' Authentication with Stripe\'s API failed';
} catch (\Stripe\Error\ApiConnection $e) {
   echo ' Network communication with Stripe failed';
} catch (\Stripe\Error\Base $e) {
   echo ' Display a very generic error to the user, and maybe send yourself an email';
} catch (Exception $e) {
   echo 'Something else happened, completely unrelated to Stripe';
}

?>
<form action="" method="post">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
		data-key="<?php echo $stripe['publishable_key']; ?>"
		data-amount="2000"
		data-name="Demo Site"
		data-email="testben@test.fr"
		data-description="2 widgets"
		data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
		data-locale="auto"
		data-zip-code="true"
		data-currency="eur">
  </script>
</form>
```

**Comment by ob-stripe** [comment] 2017-05-03 08:58
Hi @B-Poignant. This is expected behavior -- the `data-amount` and `data-currency` parameters that are provided to [Checkout](https://stripe.com/docs/checkout) are used for display purposes only. You can also not provide those parameters at all (e.g. if you're collecting card information to update a customer's saved card and are not going to immediately charge anything).

It is every merchant's responsibility to display the correct amount and currency that will actually be charged, otherwise they risk exposing themselves to chargebacks and disputes from their customers (which could in turn lead to Stripe closing the account if the chargeback rate is too high).

I'm going to close the issue as this is not a bug with Stripe's PHP library, but please feel free to reach out to Stripe's support at https://support.stripe.com/email if you have more questions or concerns about this.

**Closed by ob-stripe** 2017-05-03 08:58 UTC
