### ISSUE TITLE
No signatures found matching the expected signature for payload

### ISSUE THREAD

**Issue by subhankhalid-db** [stripe/stripe-php#884] opened 2020-02-25 09:03 UTC
Payload i received & payload in stripe event list are not the same. and getting problem in matching signature. this is my code. 
`$webhookSecret = 'whsec_Hd1BJG0dY64cRycrLU2uvBKg675adXtm';

		if( $webhookSecret )
		{
			$file = fopen("test.txt","w");
						fwrite($file, $body);
						fclose($file);
			try
			{
				$event = \Stripe\Webhook::constructEvent(
							json_encode($body),
							!empty( $_SERVER['HTTP_STRIPE_SIGNATURE'] ) ? $_SERVER['HTTP_STRIPE_SIGNATURE'] : $_SERVER['REDIRECT_HTTP_STRIPE_SIGNATURE'],
							$webhookSecret
						);
			} 
			catch (\Exception $e)
			{
				http_response_code(400);
				return json_encode( [ 'error' => $e->getMessage() ] );
			}
		}`

**Comment by remi-stripe** [comment] 2020-02-25 15:51
@subhankhalid-db For the signature verification to work, you can not alter the raw body that we send to your webhook endpoint. The signature is calculated on the raw body itself so every space, new line, indentation, etc. matters. In your code here you're explicitly calling `json_encode` on the `body` so you're altering the exact format which is why it won't work.

You need to make sure that you pass the exact raw body of the request we send you when you call  `constructEvent()`. If you don't the signatures won't match.

I'm going to close this out as it's not a bug with the library itself. If you have any follow up questions, please make sure to talk to our support team directly: https://support.stripe.com/contact

**Closed by remi-stripe** 2020-02-25 15:51 UTC
