### ISSUE TITLE
Test Card 4000000000003220 doesnt return confirmation url stripe_js

### ISSUE THREAD

**Issue by ryanm352** [stripe/stripe-php#695] opened 2019-08-15 17:52 UTC
Stripe SDK v6.43.0

After a payment intent confirmation, attempting to access the stripe_js attribute returns the following structure:

```
[next_action] => Stripe\StripeObject Object
        (
            [type] => use_stripe_sdk
            [use_stripe_sdk] => Stripe\StripeObject Object
                (
                    [type] => stripe_3ds2_fingerprint
                    [three_d_secure_2_source] => src_1F7mxLHOUQdn7wMhCTBC6TUF
                    [directory_server_name] => visa
                    [server_transaction_id] => f593a769-130c-4535-95d7-3587acd12712
                    [three_ds_method_url] =>
                    [three_ds_optimizations] =>
                    [directory_server_encryption] => Stripe\StripeObject Object
                        (
                            [directory_server_id] => A000000003
                            [algorithm] => RSA
                            [certificate] => -----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----

                            [root_certificate_authorities] => Array
                                (
                                    [0] => -----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----

                                )

                        )

                )

        )
```
meanwhile, using test card  4000000000003063  returns the following object.

```
[next_action] => Stripe\StripeObject Object
        (
            [type] => use_stripe_sdk
            [use_stripe_sdk] => Stripe\StripeObject Object
                (
                    [type] => three_d_secure_redirect
                    [stripe_js] => https://hooks.stripe.com/redirect/authenticate/src_1F7n0RHOUQdn7wMh2qVT8BPh?client_secret=src_client_secret_Fd36qjL3L5fvn8L2xjWduO53
                )

        )
```

Shouldn't the 3dSecure v2 return a url similar to the next_action above?

**Comment by remi-stripe** [comment] 2019-08-15 17:56
@ryanm352 The shape of `use_stripe_sdk` is not stable and not something you should be looking into. What this means here is really just that you need to use Stripe.js or our mobile SDKs client-side to handle the next steps.

Since this is not a bug with the library and more an API question I will be closing this but don't hesitate to reach out to our support team if you have any questions: https://support.stripe.com/contact

**Closed by remi-stripe** 2019-08-15 17:56 UTC

**Comment by blackarcanis** [comment] 2021-05-26 15:35
@remi-stripe Got the same issue today. We are using the "stripe_js" URL to redirect the user to the authentication step. However, this "stripe_js" value is not existing for 3dSecure v2, so what we should do exactly?
