### ISSUE TITLE
Having problem in accepting payment via formintor

### ISSUE THREAD

**Issue by vrashank** [stripe/stripe-php#968] opened 2020-07-11 10:44 UTC
Unrecognized request URL (GET: /v1/payment_intents/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.

When I fill the form and hit the pay now button then it shows the above error can you please tell me what the actual problem is and how can I fix it... Its really very urgent.

My domain is defencessbguru.com/checkout

**Comment by remi-stripe** [comment] 2020-07-11 18:35
@vrashank This error usually happens because your code is trying to retrieve a specific PaymentIntent id but the variable you are passing to the SDK is empty or null. You need to edit your code to ensure that the variable for the PaymentIntent id is not null or talk to the developers of your code if you didn't build it yourself.

I'm going to close this issue since it's not a bug with the library itself and you should talk to our support team for further help instead: https://support.stripe.com/contact

**Closed by remi-stripe** 2020-07-11 18:35 UTC
