### ISSUE TITLE
Received unknown parameter - Add/Edit Account

### ISSUE THREAD

**Issue by codoffer** [stripe/stripe-php#648] opened 2019-05-03 05:08 UTC
Getting an error when passing additional data for create/update custom bank account
Received unknown parameter: business_type

```
$account_values = [
                'external_account' => [
                    'object' => 'bank_account',
                    'country' => "CA",
                    'currency' => "CAD",
                    'account_holder_name' => "TEST",
                    'account_holder_type' => "company",
                    'routing_number' => $request->routing_number,
                    'account_number' => $request->account_number,
                ],
                'business_type' => "company",
                'company' => [
                    'address' => "address",
                    'name' => "name",
                    'phone' => "phone",
                ],
                'metadata' => [
                    'int_id' => $int_id
                ]
            ];

$resAccount = Stripe\Account::update($accountInfo->stripe_id, $account_values);
```

**Comment by remi-stripe** [comment] 2019-05-03 05:28
@codoffer The error here is likely due to a discrepancy in the API version you're using. `business_type`  was introduced on [2019-02-19](https://stripe.com/docs/upgrades#2019-02-19) but the API version in your Stripe account must be older than this.

I would recommend reading that part of the documentation and deciding if you want to force the API version to a more recent as documented [here](https://stripe.com/docs/api/versioning). Otherwise, you need to pass the right parameters based on your API version. You can see a table mapping the old fields to the new ones here: https://stripe.com/docs/connect/updated-requirements/accounts-arguments

I'm closing this out as it's not a bug with the library. Don't hesitate to follow up with our support team if you have any other question: https://support.stripe.com/contact

**Closed by remi-stripe** 2019-05-03 05:28 UTC
