### ISSUE TITLE
limit parameter disregarded by autoPagingIterator()

### ISSUE THREAD

**Issue by jpdelmundo** [stripe/stripe-php#928] opened 2020-05-05 07:18 UTC
In this code, the autoPagingIterator() does not stop at the limit of 3 objects. I added a "break" code to stop after the 10th object, and clearly, it exceeds the limit of 3 objects. Removing the "break" code it runs forever.
I'm guessing this can be fixed by upgrading the API version and SDK. Unfortunately, it is not an option for us right now because of the PHP version on our server (version details below).

```
\Stripe\Stripe::setApiKey('<stripe secret key>');
\Stripe\Stripe::setApiVersion('2017-12-14'); //with or without this, the problem exists
$invoices = \Stripe\Invoice::all(array(
    'limit'=>3
));

$invoice_list = array();
$count = 0;
foreach($invoices->autoPagingIterator() as $invoice) {
    $invoice_list[] = array(
        'id'=>$invoice->id
    );
    $count++;
    if ($count > 10) break;
}

echo '<pre>';
print_r($invoice_list);exit;
```

Stripe PHP SDK version: 5.8.0
PHP version: 5.3.3

**Comment by jpdelmundo** [comment] 2020-05-05 07:55
As a workaround, I tried iterating the result without the use of autoPagingIterator() but it looks like the "has_more" field always returns true even when the set returned already comprises the end of the list. So, really no way to work around this issue.

**Comment by ob-stripe** [comment] 2020-05-05 15:35
@jpdelmundo The purpose of [auto-pagination](https://stripe.com/docs/api/pagination/auto) is to automatically fetch new pages from Stripe's API until all objects have been retrieved. The `limit` parameter simply sets the maximum number of objects that can be present in each page.

If you simply want to retrieve a maximum of 3 objects, without iterating over the rest of the pages, you should not use auto-pagination at all. Instead, you can simply iterate over the contents of the [`data`](https://stripe.com/docs/api/pagination#pagination-data) attribute of the [list object](https://stripe.com/docs/api/pagination):

```php
$invoices = \Stripe\Invoice::all(array(
    'limit'=>3
));

foreach($invoices->data as $invoice) {
    // Do something with $invoice
}
```

Closing since this is working as intended, but feel free to reply.

**Closed by ob-stripe** 2020-05-05 15:35 UTC

**Comment by jpdelmundo** [comment] 2020-05-05 15:50
Ah I see. I got confused with the "limit" parameter (in the API doc example) having an impact on autoPagingIterator(), whereas when the iterator is actually used in a foreach loop, it deals with individual object. I remember working on this before and forgot about the "->data" member. Thanks for clarifying!

**Comment by ob-stripe** [comment] 2020-05-05 15:51
You're welcome, glad I could help1
